### ISSUE TITLE
File storage to a network share doesn't work after updating

### ISSUE THREAD

**Issue by axispiercesirius** [ccrisan/motioneyeos#1132]
Testing the connection says 
`Accessing network share failed: 'NoneType' object has no attribute 'lower'!`

I am using a Raspberry Pi 2B with the latest firmware

**Comment by ccrisan** [comment]
Please clear you browser's cache, refresh and try again. If the problem persists, please attach your motioneye.log file here.

**Comment by ShodaPublicity** [comment]
I am also receiving this error. Let me know if you need anything else.

RaspberryPi 3
motionEye Version: 0.37.1
Motion Version: 4.0.1+git2a140fa
motionEyeOS: 20171008

File Storage Settings:
Storage Device: Network Share
Network Server: nasew.local
Share Name: FreeNAS
Root Directory: /PiSecure

[motioneye.log](https://github.com/ccrisan/motioneyeos/files/1512648/motioneye.log)

**Comment by Jasonb11** [comment]
I am also having this error: 
I just deleted all of my log files and have a fresh motion log. Motioneyeos keeps giving errors in GUI when a change is made. Example: adding a duplicate network camera.

Here is my motioneye.log
[motioneye (1).log](https://github.com/ccrisan/motioneyeos/files/1577638/motioneye.1.log)

**Comment by Jasonb11** [comment]
@axispiercesirius @ShodaPublicity did you get anywhere with this message yet?

**Comment by ccrisan** [comment]
Guys it appears to be a bug in motionEye when username is absent. I'll make sure to fix it for the next release. In the meantime, a workaround for now would be to supply a username.

**Comment by ccrisan** [comment]
https://github.com/ccrisan/motioneye/commit/aef68011a811b681187d820dc2121807f7a2e5c3 should fix this issue. It'll be part of the next release.

**Comment by ShodaPublicity** [comment]
Hey @ccrisan, I use credentials to access my NAS so a username and password is supplied but I still have this issue. I thought that I included these fields so you would know that I have them filled but I just noticed that I did not, sorry.

**Comment by Jasonb11** [comment]
Ill give it a try.
