### ISSUE TITLE
Multiple cameras mixing files together.

### ISSUE THREAD

**Issue by shevett** [ccrisan/motioneyeos#450]
I've set up a Raspberry Pi with a USB cam and the PiCam.  In the interface, they're visible as Camera3 and Pi-Cam.  However, no matter which one I look at and look at history, I only see the images from the PiCam, even though the subtitling says "Camera3".  Screenshots are attached here:

Here's the two cameras in the overview:
![image](https://cloud.githubusercontent.com/assets/3791161/17458251/047c5d22-5bda-11e6-9177-2a2baee42903.png)

When I click on Camera3 and view history, I see:
![image](https://cloud.githubusercontent.com/assets/3791161/17458250/ef288996-5bd9-11e6-9010-060e8eda4e13.png)

I probably can manually changes the save path, but this should be handled in the interface.

**Comment by ccrisan** [comment]
What are the values of the File Storage/Root Directory options of the two cameras?

**Comment by shevett** [comment]
Here's what I'm seeing:
Storage device: Custom path
Root Directory: /data/output

I have not manually touched these since install.

I suspect the correct answer is to make that something like /data/output/picam and /data/output/camera3 - but when i add a new camera, it'll default to /data/output all the time, right?  Seems like a simple patch.

**Comment by ccrisan** [comment]
Indeed, the `/data/output` is the default for all cams. The reason is that most users have one camera per motionEyeOS instance, motionEyeOS being intended for single-board computers which are usually not that powerful.

However it may be a good idea to separate the Root Directory for cameras from the start, automatically. I will take this into consideration.

**Comment by shevett** [comment]
One last bit on this.  I manually edited the configs fro each camera specifying a new dir for each, but it looks like motioneyes needs to have the directories created by hand:

2016-08-06 15:46:16: [motioneye]    ERROR: failed to execute statvfs: [Errno 2] No such file or directory: '/data/output/picam'
2016-08-06 15:46:16: [motioneye]    ERROR: failed to execute statvfs: [Errno 2] No such file or directory: '/data/output/camera3'

Perhaps a hook on the web interface when you change the dir to say something like "This directory doesn't exist, do you want to create it?" would be helpful here.

**Comment by ibedanny** [comment]
Does anyone have a recommendation for a cost effective ir camera I can add to my motioneye OS?

**Comment by ibedanny** [comment]
WiFi IR camera.

**Comment by ccrisan** [comment]
This issue has been (partially) fixed with https://github.com/ccrisan/motioneye/commit/7585d1858b78c186f7ee01f9710ae337e81e2f7c and https://github.com/ccrisan/motioneye/commit/b40825d03fae3fbe5fcb9830cedca7794d10fe8b.

**Comment by Clem2Clone** [comment]
I'd like to see this options also. I will check your suggestions (partially fixed)
