### ISSUE TITLE
second camera movies won't upload to gdrive after adding adding second camera to rpi3 

### ISSUE THREAD

**Issue by PresidentNick** [ccrisan/motioneyeos#484]
I added a second camera to my rpi3 that already has gdrive upload. I chose the same upload settings and got a new authorization key for the second camera. I noticed nothing has been uploaded to that folder on gdrive for the second camera, the first camera is uploading fine.

Here are the log files:

[dmesg.txt](https://github.com/ccrisan/motioneyeos/files/445908/dmesg.txt)
[boot.txt](https://github.com/ccrisan/motioneyeos/files/445910/boot.txt)
[messages.txt](https://github.com/ccrisan/motioneyeos/files/445907/messages.txt)
[motioneye.txt](https://github.com/ccrisan/motioneyeos/files/445911/motioneye.txt)
[motion.txt](https://github.com/ccrisan/motioneyeos/files/445909/motion.txt)

**Comment by ccrisan** [comment]
Please try the latest prerelease. There are a few bugs regarding Google Drive that have been fixed recently.

**Comment by PresidentNick** [comment]
I've updated the pi to the latest stable 20160915 I still don't see the uploads. Does 20160915 contain the pre-release stuff you mentioned? I didn't update to pre-release at the time since I wasn't sure how to.

**Comment by ccrisan** [comment]
20160915 contains all the mentioned fixes. Please try disabling, reenabling and reconfiguring media file upload for both of your cameras. If it still doesn't work, please attach your motioneye.log file again and your config files (after removing sensitive data from them).

**Comment by PresidentNick** [comment]
Ok I've disabled, re-enabled for both cameras, I've also rebooted the pi, still don't get the videos on my google drive for the second camera. What is the name of the config file and where is it located?

**Comment by ccrisan** [comment]
You can find them at /data/etc/thread-*.conf. Otherwise, from the UI, you can download them as a configuration backup archive.

**Comment by PresidentNick** [comment]
Here are the 2 thread-*.conf in that directory.

[thread-2.txt](https://github.com/ccrisan/motioneyeos/files/487419/thread-2.txt)
[thread-1.txt](https://github.com/ccrisan/motioneyeos/files/487420/thread-1.txt)

**Comment by ccrisan** [comment]
@PresidentNick could you please attach your motioneye.log now, after you have upgraded to 20160915? You config files look fine.

**Comment by PresidentNick** [comment]
[motioneye.txt](https://github.com/ccrisan/motioneyeos/files/489739/motioneye.txt)

**Comment by ccrisan** [comment]
@PresidentNick for the second camera, you have enabled Movies and set Recording Mode to Motion Triggered, but the Motion Detection mechanism is disabled. That's the reason why you see no movies for the second camera.

**Comment by PresidentNick** [comment]
Wow, I'm so dumb, I didn't catch that. Thank you for pointing that out!
